### ISSUE TITLE
 Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by andybuki** [jbaiter/pdiiif#22]
Hi, after last update i get following issue:

You can test it using my manifest: [https://iiif.crossasia.org/s/dllm/madoc/api/manifests/20817/export/3.0]

`hub-77f45d8c.js:6 Error while generating cover page TypeError: Cannot read properties of undefined (reading 'type')
    at ab.get (index-1587c411.js:48:81127)
    at i (index-1587c411.js:17:32273)
    at Object.i [as getBestThumbnailAtSize] (index-1587c411.js:17:32900)
    at Pb (index-1587c411.js:50:2214)
    at e1 (index-1587c411.js:101:16175)
    at t1 (index-1587c411.js:101:19039)
    at async x (index-1587c411.js:102:46184)
    at async HTMLButtonElement.N (index-1587c411.js:102:48214)
(anonymous) @ hub-77f45d8c.js:6
hub-77f45d8c.js:6 TypeError: Cannot read properties of undefined (reading 'type')
    at ab.get (index-1587c411.js:48:81127)
    at i (index-1587c411.js:17:32273)
    at Object.i [as getBestThumbnailAtSize] (index-1587c411.js:17:32900)
    at Pb (index-1587c411.js:50:2214)
    at e1 (index-1587c411.js:101:16175)
    at t1 (index-1587c411.js:101:19039)
    at async x (index-1587c411.js:102:46184)
    at async HTMLButtonElement.N (index-1587c411.js:102:48214)`

Do you have any ideas?

**Comment by andybuki** [comment]
Sorry i think problem is on my side. I close the issue

**Comment by jbaiter** [comment]
The problem is that the URL https://iiif.crossasia.org/s/dllm/madoc/api/manifests/20817/export/3.0 is not the identifier for the manifest.
The manifest's `id` is https://iiif2.crossasia.org/s/dllm/madoc/api/manifests/20817/export/3.0, and `iiif2.crossasia.org` is not a domain that can be resolved with public DNS servers.
